export const actionTypes = {
	/**
	 * CART
	 */
	SET_ITEMS_TO_CART: 'SET_ITEMS_TO_CART',
	ADD_TO_CART: 'ADD_TO_CART',
	CHECKOUT_USER_PAYMENT: 'CHECKOUT_USER_PAYMENT',

	/**
	 * Products
	 */
	DISPLAY_PRODUCTS: 'DISPLAY_PRODUCTS',
	BUILD_PRODUCT: 'BUILD_PRODUCT',
	BUILD_PRODUCT_ERROR: 'BUILD_PRODUCT_ERROR',
	REMOVE_PRODUCT: 'REMOVE_PRODUCT',
};
